In [13]:
import tensorflow as tf
from tensorflow import keras
from keras.layers import BatchNormalization,Dropout
import matplotlib.pyplot as plt
%matplotlib inline
import numpy as np
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()

In [14]:
(xtrain,ytrain),(xtest,ytest) = keras.datasets.mnist.load_data()

In [15]:
xtrain = xtrain.astype("float32")/255
xtest = xtest.astype("float32")/255

In [16]:
xtrainFlattened = xtrain.reshape(60000,-1)
xtestFlattened = xtest.reshape(10000,-1)

In [4]:
xtrainFlattened = scaler.fit_transform(xtrainFlattened)
xtestFlattened  =scaler.transform(xtestFlattened)

In [17]:
xtrain = tf.Variable(xtrain)
ytrain = tf.Variable(ytrain)
xtest = tf.Variable(xtest)
ytest = tf.Variable(ytest)
xtrainFlattened = tf.Variable(xtrainFlattened)
xtestFlattened = tf.Variable(xtestFlattened)

In [6]:
model = keras.Sequential([
    keras.layers.Dense(10,input_shape=(784,),activation = "sigmoid")
])

model.compile(
    optimizer="adam",
    loss="sparse_categorical_crossentropy",
    metrics=["accuracy"]
)

model.fit(xtrainFlattened,ytrain,epochs=5)


Epoch 1/5
1875/1875 [==============================] - 6s 3ms/step - loss: 0.4730 - accuracy: 0.8764
Epoch 2/5
1875/1875 [==============================] - 5s 3ms/step - loss: 0.3039 - accuracy: 0.9153
Epoch 3/5
1875/1875 [==============================] - 4s 2ms/step - loss: 0.2835 - accuracy: 0.9197
Epoch 4/5
1875/1875 [==============================] - 4s 2ms/step - loss: 0.2733 - accuracy: 0.9232
Epoch 5/5
1875/1875 [==============================] - 5s 2ms/step - loss: 0.2666 - accuracy: 0.9257


In [7]:
ypred = model.predict(xtestFlattened)

313/313 [==============================] - 1s 2ms/step


In [8]:
ypredLabels = [np.argmax(i) for i in ypred]

In [9]:
tf.math.confusion_matrix(labels=ytest,predictions=ypredLabels)

<tf.Tensor: shape=(10, 10), dtype=int32, numpy=
array([[ 963,    0,    2,    2,    0,    5,    5,    2,    1,    0],
       [   0, 1117,    3,    2,    0,    1,    4,    2,    6,    0],
       [   3,    9,  936,   16,    7,    4,   10,    9,   33,    5],
       [   2,    0,   20,  926,    0,   23,    2,   10,   18,    9],
       [   2,    1,    8,    1,  911,    0,    6,    4,    8,   41],
       [   8,    2,    7,   34,   10,  781,    9,    6,   28,    7],
       [  12,    3,   10,    1,    8,   16,  903,    2,    3,    0],
       [   1,    6,   25,    5,    6,    1,    0,  944,    3,   37],
       [   7,   10,    6,   21,    9,   30,    8,   11,  863,    9],
       [  10,    7,    2,   11,   26,    6,    0,   16,    5,  926]])>

In [24]:
callback = tf.keras.callbacks.EarlyStopping(
    monitor="val_loss",
    min_delta=0,
    patience=1,
    verbose=1,
    mode="auto",
    baseline=None,
    restore_best_weights=False,
    start_from_epoch=0,
)

In [33]:
model = keras.Sequential([
    keras.layers.Dense(100,input_shape=(784,),activation = "relu",kernel_initializer="he_uniform"),
    Dropout(0.2),
    BatchNormalization(),
    keras.layers.Dense(100,activation = "relu",kernel_initializer="he_uniform"),
    Dropout(0.2),
    BatchNormalization(),
    keras.layers.Dense(10,activation = "sigmoid")
])

model.compile(
    optimizer="adam",
    loss="sparse_categorical_crossentropy",
    metrics=["accuracy"],
)

model.fit(xtrainFlattened,ytrain,epochs=10,callbacks=[callback],batch_size=100,validation_data=(xtestFlattened,ytest))


Epoch 1/10
600/600 [==============================] - 7s 8ms/step - loss: 0.4269 - accuracy: 0.8705 - val_loss: 0.1565 - val_accuracy: 0.9528
Epoch 2/10
600/600 [==============================] - 5s 8ms/step - loss: 0.2040 - accuracy: 0.9394 - val_loss: 0.1216 - val_accuracy: 0.9641
Epoch 3/10
600/600 [==============================] - 5s 8ms/step - loss: 0.1595 - accuracy: 0.9512 - val_loss: 0.1066 - val_accuracy: 0.9675
Epoch 4/10
600/600 [==============================] - 5s 8ms/step - loss: 0.1378 - accuracy: 0.9581 - val_loss: 0.0963 - val_accuracy: 0.9691
Epoch 5/10
600/600 [==============================] - 4s 7ms/step - loss: 0.1196 - accuracy: 0.9628 - val_loss: 0.0928 - val_accuracy: 0.9722
Epoch 6/10
600/600 [==============================] - 5s 8ms/step - loss: 0.1079 - accuracy: 0.9667 - val_loss: 0.0830 - val_accuracy: 0.9748
Epoch 7/10
600/600 [==============================] - 5s 8ms/step - loss: 0.0997 - accuracy: 0.9692 - val_loss: 0.0854 - val_accuracy: 0.9733
Epoch 

In [35]:
ypred = model.predict(xtestFlattened)
ypredLabels = [np.argmax(i) for i in ypred]
tf.math.confusion_matrix(labels=ytest,predictions=ypredLabels)

313/313 [==============================] - 1s 4ms/step


<tf.Tensor: shape=(10, 10), dtype=int32, numpy=
array([[ 971,    0,    1,    0,    1,    1,    2,    0,    2,    2],
       [   0, 1129,    0,    2,    0,    1,    1,    0,    2,    0],
       [   2,    0, 1010,    4,    1,    0,    2,    6,    7,    0],
       [   0,    0,    5,  991,    0,    1,    0,    4,    0,    9],
       [   1,    0,    3,    0,  957,    0,    6,    1,    0,   14],
       [   3,    0,    0,   21,    3,  842,    5,    3,    5,   10],
       [   8,    3,    0,    1,    6,    5,  930,    0,    5,    0],
       [   0,    8,   11,    6,    1,    0,    0,  990,    0,   12],
       [   1,    0,    3,    7,    7,    6,    1,    3,  941,    5],
       [   4,    3,    1,    8,   14,    1,    0,    6,    0,  972]])>

In [27]:
model.evaluate(xtestFlattened,ytest)

313/313 [==============================] - 1s 4ms/step - loss: 0.0977 - accuracy: 0.9684


[0.09772079437971115, 0.9684000015258789]

In [34]:
model.variables

[<tf.Variable 'dense_30/kernel:0' shape=(784, 100) dtype=float32, numpy=
 array([[-0.00648864, -0.05479087,  0.03818708, ...,  0.02373294,
         -0.00210492, -0.04553395],
        [-0.04712306,  0.05629351, -0.06600055, ...,  0.07104614,
         -0.00253966,  0.06534404],
        [ 0.00323717, -0.0765409 , -0.06522316, ..., -0.04283674,
          0.0022857 ,  0.07341994],
        ...,
        [ 0.01082513, -0.0039693 ,  0.02737585, ..., -0.05621494,
         -0.0405098 , -0.0324084 ],
        [ 0.04279987, -0.01495498, -0.01254784, ..., -0.07507891,
         -0.06567818, -0.06860581],
        [-0.07208806, -0.02178935, -0.07205541, ..., -0.07292429,
         -0.01404116,  0.04393622]], dtype=float32)>,
 <tf.Variable 'dense_30/bias:0' shape=(100,) dtype=float32, numpy=
 array([-0.06153723,  0.01271321,  0.04974916,  0.0865702 ,  0.05751715,
        -0.02003264,  0.03132933, -0.01158573,  0.03644713,  0.04326998,
        -0.04831693, -0.00038837, -0.02421392,  0.02671138,  0.01333852

In [18]:
import keras_tuner as kt

In [19]:
def build_model(hp):
    model = keras.Sequential()

    counter = 0

    for i in range(hp.Int("num_layers",min_value=1,max_value=10)):
        if(not counter):
            model.add(
                keras.layers.Dense(          
                    hp.Int(f"units {i}",min_value=8,max_value=128,step=8),
                    activation = hp.Choice(f"activation {i}",values=["relu","tanh","linear","sigmoid"]),
                    input_dim=784,
                    kernel_initializer=hp.Choice(f"kernel {i}",values=["he_normal","he_uniform","glorot_normal","glorot_uniform"])
                )
            )
            model.add(
                Dropout(
                    hp.Choice(f"Dropout {i}",values=[0.2,0.3,0.5,0.6,0.8])
                )
            )
            model.add(BatchNormalization())
            counter+=1
        else:
            model.add(
                keras.layers.Dense(          
                    hp.Int(f"units {i}",min_value=8,max_value=128,step=8),
                    activation = hp.Choice(f"activation {i}",values=["relu","tanh","linear","sigmoid"]),
                    kernel_initializer=hp.Choice(f"kernel {i}",values=["he_normal","he_uniform","glorot_normal","glorot_uniform"])
                )
            )
            model.add(
                Dropout(
                    hp.Choice(f"Dropout {i}",values=[0.2,0.3,0.5,0.6,0.8])
                )
            )
            model.add(BatchNormalization())

    model.add(keras.layers.Dense(10,activation="relu"))
    model.compile(
        optimizer = hp.Choice("optmizer",values=["rmsprop","adadelta","adam","sgd","nadam"]),
        loss="sparse_categorical_crossentropy",
        metrics=["accuracy"],
    )
    return model

    

    

In [22]:
tuner = kt.GridSearch(build_model,objective="val_accuracy",max_trials=5)

In [23]:
tuner.search(xtrainFlattened,ytrain,epochs=10,validation_data=(xtestFlattened,ytest),batch_size=100)

Trial 5 Complete [00h 00m 23s]
val_accuracy: 0.5756000280380249

Best val_accuracy So Far: 0.6205999851226807
Total elapsed time: 00h 01m 56s
